### ISSUE TITLE
A'zo akkaunti sahifasini yaratish

### ISSUE THREAD

**Issue by bahriddin** [IT-forward/IT-forward.github.io#13]
Ustoz-shogird daraxti va boshqa joylardan a'zo profili ustiga bosganda boradigan sahifani yaratishimiz kerak.
Ichida bo'lishi kerak qismlar:
- rasm
- ism-familiya
- o'zi haqida qisqacha
- bog'lanish uchun github, linkedin va boshqa linklar
- ustozi kim ekanligi
- shogirdlari soni: bevosita va bilvosita (shogirdlarining shogirdlari soni). Shu va tepadagi qism uchun ustoz-shogir daraxtiga borish uchun link qo'shish kerak
- portfoliosi: qilgan loyihalari skrinshot, nomi, Github linki va Netlify/Vercel linki

Boshlanishiga shablonimiz muallifi (Figmadagi **👋🏼 Hello** sahifasi) va lending page stilidan foydalansangiz bo'ladi:

![image](https://user-images.githubusercontent.com/3971918/119821689-31d34280-bf36-11eb-9a5e-18ad62634d06.png)

**Comment by Husan-Eshonqulov** [comment]
Agar Otabek akam bu vazifani olmayman desalar, manda shu narsaga qiziqish tuyuldi

**Comment by bahriddin** [comment]
@husan-eshonqulov shu PRni qanday run qilish kerak edi?
